### ISSUE TITLE
[feature] Pre-built binaries 

### ISSUE THREAD

**Issue by Hyphrio** [bgpkit/monocle#52]
I think having pre-built binaries would make it easier for end-users to use the program. Integration with `cargo-binstall` could also be nice.

**Comment by digizeph** [comment]
Thanks for the suggestion! I will look into this soon!

**Comment by digizeph** [comment]
@Hyphrio The new `v0.5.2` release and the future ones will come with pre-built binaries uploaded to the release. We have also added a homebrew tap for it. If you are on macos, you can install `monocle` with `brew install bgpkit/tap/monocle` now.

**Comment by digizeph** [comment]
@Hyphrio `monocle` is now installable via `cargo binstall monocle`. It currently supports latest debian-based OSes and macos. Please let me know if you encounter any other issues. Thanks!
