### ISSUE TITLE
monocle radar stats possible to go back in the time?

### ISSUE THREAD

**Issue by shyamkkhadka** [bgpkit/monocle#69]
It would be nice to see radar stats to see historical records. Same for monocle radar pfx2as. Any plan to add this feature in the future?

**Comment by digizeph** [comment]
Cloudflare Radar currently does not support historical look up for routing information that used in "monocle radar" command. For that, you may want to check out my historical data archive at https://data.bgpkit.com

**Comment by shyamkkhadka** [comment]
Got it. Thanks!

**Comment by digizeph** [comment]
`monocle rpki` uses Cloudflare's RPKI validator endpoint and it does not support historical look up at the moment. We have an separate project that can do historical lookup at daily granularity using RIPE RIS's daily RPKI VRP dump: https://github.com/bgpkit/wayback-rpki
You can set up a service yourself (takes roughly 2 GB of memory to run and bootstrap takes about 30 seconds). You can also try our experimental API based on that code base: https://alpha.api.bgpkit.com/docs#tag/alpha/GET/roas

For anything more granular than daily, you might need to use [RPKIViews](https://www.rpkiviews.org/).

**Comment by shyamkkhadka** [comment]
Thanks for the information.
